[monitor:///var/log/ztaleaks/nftables]
disabled = false
index = main
sourcetype = _json

[monitor:///var/log/ztaleaks/snort]
disabled = false
index = main
sourcetype = _json

[monitor:///var/log/ztaleaks/snort-internal]
disabled = false
index = main
sourcetype = _json

[monitor:///var/log/ztaleaks/envoy]
disabled = false
index = main
sourcetype = _json

[monitor:///var/log/ztaleaks/business-logic]
disabled = false
index = main
sourcetype = _json

[monitor:///var/log/ztaleaks/mongodb]
disabled = false
index = main
sourcetype = _json