version: '3.8'

services:
  test_client:
    build:
      context: ../../
      dockerfile: tests/clients/Dockerfile
    networks:
      - front-net

  test_client_2:
    build:
      context: ../../
      dockerfile: tests/clients/Dockerfile.python
    networks:
      - front-net

networks:
  front-net:
    name: docker-compose_front-net
    external: true
