apiVersion: v1
kind: Service
metadata:
  name: business-db
  labels:
    app: business-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: business-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: business-db
  labels:
    app: business-db
spec:
  serviceName: "business-db"
  replicas: 1
  selector:
    matchLabels:
      app: business-db
  template:
    metadata:
      labels:
        app: business-db
    spec:
      containers:
      - name: business-db
        image: ztaleaks/business-db
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongodb
        envFrom:
        - secretRef:
            name: ztaleaks-secrets
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: init-scripts
        configMap:
          name: business-db-init
