#!/usr/sbin/nft -f

table inet filter {
    # Indirizzi IP bloccati di esempio (utile per i test di drop)
    set blocked_ips {
        type ipv4_addr
        elements = { 10.99.99.99,172.18.0.10 }
    }

    chain input {
        # Imposta la policy di default a DROP per bloccare tutto il resto
        type filter hook input priority 0; policy drop;

        # Accetta il traffico locale
        iif "lo" accept

        # Accetta il traffico per connessioni già stabilite e correlate
        ct state established,related accept

        # Rate-limiting contro TCP SYN Flood (max 20 syn/sec)
        tcp flags & (fin|syn|rst|ack) == syn limit rate over 20/second log prefix "fw-syn-flood-drop: " group 100 drop

        # Drop delle richieste provenienti dagli IP bloccati verso la porta di Envoy
        ip saddr @blocked_ips tcp dport ENV_ENVOY_PORT log prefix "fw-drop: " group 100 reject

        # Accetta e logga le nuove connessioni per la porta locale indicata dall'environment (Envoy)
        tcp dport ENV_ENVOY_PORT ct state new log prefix "fw-accept: " group 100 accept     
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy drop;

        # Accetta il traffico locale
        oif "lo" accept

        # Accetta stabilite e correlate in uscita
        ct state established,related accept

        # Accetta log di sistema (splunk UF) o DNS (53) o connessioni interne note
        # Per un container l'uscita limitata puo' richiedere 53 UDP, e chiamate all'orchestator / envoy (interne/esterne)
        # Permettiamo tutto il traffico verso la nostra rete docker (assumendo /16 o specifiche) o internet, ma droppiamo l'inatteso.
        # Oppure permettiamo solo il necessario per un microservizio
        tcp dport { 53, 80, 443, 8080, 8081, 8082, 8088, 8181 } accept
        udp dport 53 accept
        
        # Loggare il drop in uscita
        log prefix "fw-egress-drop: " group 100 drop
    }
}
