[global]
logfile=/var/log/ulogd.log
loglevel=1

plugin="ulogd_inppkt_NFLOG.so"
plugin="ulogd_filter_IFINDEX.so"
plugin="ulogd_filter_IP2STR.so"
plugin="ulogd_filter_PRINTPKT.so"
plugin="ulogd_output_LOGEMU.so"
plugin="ulogd_raw2packet_BASE.so"

stack=log1:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,print1:PRINTPKT,emu1:LOGEMU

[log1]
group=100

[emu1]
file="/var/log/ulogd-syslogemu.log"
sync=1
